#!/bin/bash
export TF_VAR_region="ap-south-1"
export TF_VAR_ami_id="ami-0f918f7e67a3323f0"
export TF_VAR_instance_type="t2.micro"
export TF_VAR_key_name="mb-lap-key"
export TF_VAR_name_tag="techeazy-dev"
export TF_VAR_bucket_name="techeazy-dev-ec2-logs-bucket"
export TF_VAR_app_repo_url="https://github.com/techeazy-consulting/techeazy-devops.git"
export TF_VAR_app_config_json_url="https://raw.githubusercontent.com/shahfahed/tech_eazy_devops_shahfahed_dev_config/refs/heads/main/configs/dev.json"
export TF_VAR_stage="dev"
export TF_VAR_alert_email="shahfahed88@gmail.com"
export TF_VAR_cw_config_jason_url="https://raw.githubusercontent.com/shahfahed/tech_eazy_devops_shahfahed_dev_config/refs/heads/main/cloud_watch_config/config.json"